title: Andy Wang # your name (or website title) here
logo: "/images/round_profile_picture_resized.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data scientist with 1+ years of precision marketing experience in analytics, predictive model , data viz and a master degree in statistics from Chengchi University.Currently at Sinyi Realty Inc.
  <br><br>
  <br><br>
  <br><br>
  
  <a href="https://www.linkedin.com/in/%E6%8F%86%E5%BA%AD-%E7%8E%8B-691209202/">View My LinkedIn Profile</a> 
  
  <br><br>
  <br><br>
 
  
theme: jekyll-theme-minimal
